# Generated by Django 3.1.7 on 2021-03-25 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=200, verbose_name='Objetivo')),
                ('data', models.DateField(verbose_name='Data')),
                ('inicio', models.DateField(verbose_name='Inicio')),
                ('fim', models.DateField(verbose_name='Fim')),
                ('quem', models.CharField(max_length=100, verbose_name='Objetivo')),
                ('descricao', models.TextField(max_length=400, verbose_name='Descrição')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='PDCAItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('descricao', models.TextField(max_length=400, verbose_name='Descrição')),
                ('pdca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdca.pdca', verbose_name='PDCA')),
            ],
        ),
    ]
